### ISSUE TITLE
LicenseChecker 1.2.1 is not compatible with Liferay 7.3+

### ISSUE THREAD

**Issue by mshabarov** [vaadin/portlet#192]
- Description of the bug
LicenseChecker crashes to 
```
java.lang.NoSuchMethodError:
            com.sun.jna.Native.load(Ljava/lang/String;Ljava/lang/Class;Ljava/util/Map;)Lcom/sun/jna/Library;
```
due to Liferay 7.3 running with `jna` dependency older than Vaadin's `jna-5.7.0`

- Minimal reproducible example
1. Checkout `feature/liferay` branch
2. Uncomment 
```
    LicenseChecker.checkLicense(VaadinPortletService.PROJECT_NAME,
    VaadinPortletService.getPortletVersion());
```
in `PortletWebComponentBootstrapHandler` and `PortletBootstrapHandler`
3. mvn install the vaadin-portlet artifact
4. Build and deploy address book demo portlets using the installed artifact into Liferay 7.3 container.
5. Notice the exception on portlet render.

- Expected and actual behavior
No exception is thrown
- Server logs 
- Versions:
    - Vaadin Portlet version - feature/liferay branch
    - Flow version 2.7.5
    - Portal (Pluto) version -
    - Java version 11
    - OS version MacOS
    - Browser version (if applicable) Chrome 95
    - Liferay 7.3

**Comment by mshabarov** [comment]
On my machine it fails with `com.liferay.portal.kernel.portlet.PortletContainerException: javax.servlet.ServletException: java.lang.NoClassDefFoundError: com/sun/jna/platform/mac/IOKit$IORegistryEntry` just after adding the portlet to the page.

Liferay 7.3+ uses `net.java.dev.jna:jna` of version `4.1.0` whereas the Vaadin license checker uses `5.8.0` (via `oshi-core`), which causes `NoClassDefFoundError` because the used in LC methods/classes are not present in the older version.

Possible solution is to configure third-party jna dependency in Liferay to be more recent, as described here https://help.liferay.com/hc/en-us/articles/360017878032-Configuring-Dependencies and here https://help.liferay.com/hc/en-us/articles/360018162491-Resolving-Third-Party-Library-Package-Dependencies-

**Comment by mshabarov** [comment]
Works with license checker version `1.2.0` included in v14.8.0, no errors on my side when running with Liferay 7.3.7-ga8.

**Comment by mshabarov** [comment]
Now I'm able to reproduce the issue.
Indeed, when running in dev mode and being added to the page, the exception is thrown.

Solution: copy `net.java.dev.jna:jna:5.7.0` and `net.java.dev.jna:jna-platform:5.7.0` to `{liferay.home}/tomcat-{version}/webapps/ROOT/WEB-INF/lib/` in order to force Liferay use the version you want.
Note that the file name should differ from the existing file `jna.jar`, for example `jna-5.7.0.jar`.

Download:
https://mvnrepository.com/artifact/net.java.dev.jna/jna/5.7.0
https://mvnrepository.com/artifact/net.java.dev.jna/jna-platform/5.7.0

Liferay Docs:
https://learn.liferay.com/dxp/latest/en/building-applications/reference/jars-excluded-from-wabs.html
